apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance
spec:
  replicas: 3
  selector:
    matchLabels:
      app: finance
    spec:
      containers:
      - name: finance
        image: rossning92/finance
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          ports:
            - containerPort: 5000
              name: finance

---
apiVersion: v1
kind: Service
metadata:
  name: finance-np-service
spec:
  selector:
    app: finance
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
  # nodePort: 30080 